set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"
set -g xterm-keys on

set -g mouse on

# Set prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-H next-window

bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R
bind h split-window -h
bind v split-window -v
bind x kill-pane
bind k kill-window

set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-save-interval '5'
set -g @continuum-restore 'off'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "basic"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -g @catppuccin_status_background "none"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

run '~/.tmux/plugins/tpm/tpm'
