#!/bin/sh

# Super+Return terminal
riverctl map normal Super Return spawn alacritty

# Super+D for app launcher
riverctl map normal Super D spawn '/bin/sh -c wofi --show drun'

# Super+Q close window
riverctl map normal Super Q close

# Super+Shift+Q exit session
riverctl map normal Super+Shift Q exit

# Super+VIM to move between windows
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up

# Super+Shift+VIM to swap the focused view with the l/r/t/b
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift L swap right
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up

# Super+V for toggle float
riverctl map normal Super V toggle-float

# Super+F to toggle fullscreenwlr-randr --output eDP-1 --off
riverctl map normal Super F toggle-fullscreen

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100wlr-randr --output eDP-1 --off
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Control+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Control+Shift H resize horizontal -100
riverctl map normal Super+Control+Shift J resize vertical 100
riverctl map normal Super+Control+Shift K resize vertical -100
riverctl map normal Super+Control+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super $i set-focused-tags $tags

  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal Super+Shift $i set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control $i toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x000000
riverctl border-color-focused 0xc1c1c1
riverctl border-color-unfocused 0x565656

# Set keyboard repeat rate
riverctl set-repeat 50 300

# All windows have a border
riverctl rule-add ssd

# Monitor Config
wlr-randr --output eDP-1 --off
wlr-randr --output HDMI-A-1 --pos 0,0 --mode 3840x2160 --scale 1.5

# Keyboard Config
riverctl keyboard-layout de

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &
