#!/bin/bash


choice=$( echo -e "  Poweroff\n  Reboot\n  Suspend\n  Lock\n  Logout" | wofi -i --dmenu --width 350 --height 250 | awk '{print tolower($2)}' )

case $choice in 
  poweroff)
    shutdown now
    ;;
  reboot)
    ;&
  suspend)
    systemctl $choice
    ;;
  lock)
    swaylock -f -c 000000 && swayidle -w timeout 30 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 60 'systemctl suspend'
    ;;
  logout)
    hyprctl dispatch exit 1
    ;;
esac
