[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.normal]
black = "#212121"
blue = "#5078ba"
cyan = "#50baa4"
green = "#54a858"
magenta = "#a854a4"
red = "#a32d2d"
white = "#d5d8da"
yellow = "#e2c81b"

[colors.primary]
background = "#030303"
foreground = "#eeeeee"
